import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--dm-sans",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const tomatoGrotesk = localFont({
  src: [
    { path: "./fonts/TomatoGrotesk-Regular.63ff49eb.otf", weight: "400" },
    { path: "./fonts/TomatoGrotesk-Medium.8b894f94.otf", weight: "500" },
    { path: "./fonts/TomatoGrotesk-SemiBold.1183d758.otf", weight: "600" },
  ],
  variable: "--font-tomato-grotesk",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${dmSans.variable} ${tomatoGrotesk.variable} antialiased`}>{children}</body>
    </html>
  );
}
